import { Data } from "@/utils";

export const employeesData: Data = [
  {
    name: "Aline Santoso",
    "Data Modeling": 4,
    "ETL/ELT": 3,
    "Cloud Data": 1,
    "Big Data": 1,
    Orchestration: 1,
    "Machine Learning": 1,
    MLOps: 1,
    "Deep Learning": 1,
    Statistics: 3,
    "Generative AI": 1,
    Bioinformatics: 1,
    SAS: 1,
    "Data Science Tools": 3,
    "Clinical Data": 1,
    Research: 3,
    EDA: 4,
    SQL: 4,
    "BI Tools": 4,
    Metadata: 1,
    Governance: 1,
  },
  {
    name: "Edward (Ned) Booker",
    "Data Modeling": 2,
    "ETL/ELT": 1,
    "Cloud Data": 3,
    "Big Data": 1,
    Orchestration: 1,
    "Machine Learning": 5,
    MLOps: 5,
    "Deep Learning": 5,
    Statistics: 4,
    "Generative AI": 4,
    Bioinformatics: 1,
    SAS: 2,
    "Data Science Tools": 5,
    "Clinical Data": 2,
    Research: 5,
    EDA: 5,
    SQL: 4,
    "BI Tools": 2,
    Metadata: 2,
    Governance: 1,
  },
  {
    name: "Tom Harding",
    "Data Modeling": 2,
    "ETL/ELT": 3,
    "Cloud Data": 4,
    "Big Data": 4,
    Orchestration: 1,
    "Machine Learning": 5,
    MLOps: 5,
    "Deep Learning": 5,
    Statistics: 5,
    "Generative AI": 5,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 5,
    "Clinical Data": 2,
    Research: 4,
    EDA: 5,
    SQL: 5,
    "BI Tools": 3,
    Metadata: 1,
    Governance: 3,
  },
  {
    name: "Sai Gaddam",
    "Data Modeling": 4,
    "ETL/ELT": 4,
    "Cloud Data": 4,
    "Big Data": 3,
    Orchestration: 4,
    "Machine Learning": 1,
    MLOps: 1,
    "Deep Learning": 1,
    Statistics: 1,
    "Generative AI": 1,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 2,
    "Clinical Data": 2,
    Research: 2,
    EDA: 4,
    SQL: 4,
    "BI Tools": 4,
    Metadata: 4,
    Governance: 4,
  },
  {
    name: "Zilai Feng",
    "Data Modeling": 3,
    "ETL/ELT": 3,
    "Cloud Data": 3,
    "Big Data": 1,
    Orchestration: 1,
    "Machine Learning": 1,
    MLOps: 2,
    "Deep Learning": 1,
    Statistics: 1,
    "Generative AI": 2,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 3,
    "Clinical Data": 2,
    Research: 2,
    EDA: 5,
    SQL: 5,
    "BI Tools": 5,
    Metadata: 3,
    Governance: 1,
  },
  {
    name: "Jens Sommerfeld",
    "Data Modeling": 3,
    "ETL/ELT": 3,
    "Cloud Data": 3,
    "Big Data": 2,
    Orchestration: 2,
    "Machine Learning": 1,
    MLOps: 2,
    "Deep Learning": 2,
    Statistics: 1,
    "Generative AI": 2,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 1,
    "Clinical Data": 2,
    Research: 2,
    EDA: 4,
    SQL: 4,
    "BI Tools": 4,
    Metadata: 1,
    Governance: 1,
  },
  {
    name: "Justin Lam",
    "Data Modeling": 3,
    "ETL/ELT": 3,
    "Cloud Data": 3,
    "Big Data": 4,
    Orchestration: 2,
    "Machine Learning": 1,
    MLOps: 1,
    "Deep Learning": 1,
    Statistics: 1,
    "Generative AI": 3,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 4,
    "Clinical Data": 2,
    Research: 2,
    EDA: 4,
    SQL: 5,
    "BI Tools": 1,
    Metadata: 1,
    Governance: 4,
  },
  {
    name: "Siva Nadella",
    "Data Modeling": 3,
    "ETL/ELT": 4,
    "Cloud Data": 3,
    "Big Data": 4,
    Orchestration: 3,
    "Machine Learning": 2,
    MLOps: 1,
    "Deep Learning": 2,
    Statistics: 2,
    "Generative AI": 2,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 1,
    "Clinical Data": 2,
    Research: 2,
    EDA: 1,
    SQL: 3,
    "BI Tools": 3,
    Metadata: 1,
    Governance: 3,
  },
  {
    name: "Sarbjit Sarkaria",
    "Data Modeling": 4,
    "ETL/ELT": 5,
    "Cloud Data": 5,
    "Big Data": 5,
    Orchestration: 5,
    "Machine Learning": 5,
    MLOps: 3,
    "Deep Learning": 5,
    Statistics: 3,
    "Generative AI": 4,
    Bioinformatics: 3,
    SAS: 2,
    "Data Science Tools": 5,
    "Clinical Data": 1,
    Research: 1,
    EDA: 4,
    SQL: 4,
    "BI Tools": 3,
    Metadata: 3,
    Governance: 3,
  },
  {
    name: "Siavash Ghaffari",
    "Data Modeling": 4,
    "ETL/ELT": 4,
    "Cloud Data": 3,
    "Big Data": 3,
    Orchestration: 2,
    "Machine Learning": 5,
    MLOps: 4,
    "Deep Learning": 5,
    Statistics: 4,
    "Generative AI": 1,
    Bioinformatics: 5,
    SAS: 4,
    "Data Science Tools": 5,
    "Clinical Data": 1,
    Research: 5,
    EDA: 2,
    SQL: 2,
    "BI Tools": 2,
    Metadata: 2,
    Governance: 2,
  },
  {
    name: "Brian Carter",
    "Data Modeling": 2,
    "ETL/ELT": 2,
    "Cloud Data": 1,
    "Big Data": 1,
    Orchestration: 2,
    "Machine Learning": 2,
    MLOps: 2,
    "Deep Learning": 2,
    Statistics: 4,
    "Generative AI": 2,
    Bioinformatics: 4,
    SAS: 5,
    "Data Science Tools": 5,
    "Clinical Data": 3,
    Research: 5,
    EDA: 5,
    SQL: 1,
    "BI Tools": 2,
    Metadata: 2,
    Governance: 2,
  },
  {
    name: "Gabriel Brock",
    "Data Modeling": 3,
    "ETL/ELT": 3,
    "Cloud Data": 5,
    "Big Data": 3,
    Orchestration: 2,
    "Machine Learning": 5,
    MLOps: 4,
    "Deep Learning": 3,
    Statistics: 5,
    "Generative AI": 4,
    Bioinformatics: 3,
    SAS: 4,
    "Data Science Tools": 5,
    "Clinical Data": 2,
    Research: 3,
    EDA: 5,
    SQL: 3,
    "BI Tools": 3,
    Metadata: 2,
    Governance: 3,
  },
  {
    name: "Shuyu Fan",
    "Data Modeling": 5,
    "ETL/ELT": 4,
    "Cloud Data": 3,
    "Big Data": 1,
    Orchestration: 1,
    "Machine Learning": 3,
    MLOps: 1,
    "Deep Learning": 1,
    Statistics: 5,
    "Generative AI": 1,
    Bioinformatics: 3,
    SAS: 5,
    "Data Science Tools": 5,
    "Clinical Data": 5,
    Research: 5,
    EDA: 4,
    SQL: 4,
    "BI Tools": 1,
    Metadata: 3,
    Governance: 3,
  },
  {
    name: "Oisin Bates",
    "Data Modeling": 4,
    "ETL/ELT": 4,
    "Cloud Data": 4,
    "Big Data": 4,
    Orchestration: 4,
    "Machine Learning": 1,
    MLOps: 1,
    "Deep Learning": 2,
    Statistics: 2,
    "Generative AI": 1,
    Bioinformatics: 1,
    SAS: 2,
    "Data Science Tools": 4,
    "Clinical Data": 3,
    Research: 2,
    EDA: 3,
    SQL: 4,
    "BI Tools": 3,
    Metadata: 3,
    Governance: 4,
  },
  {
    name: "Videesh Guduru",
    "Data Modeling": 2,
    "ETL/ELT": 2,
    "Cloud Data": 3,
    "Big Data": 2,
    Orchestration: 2,
    "Machine Learning": 2,
    MLOps: 2,
    "Deep Learning": 2,
    Statistics: 2,
    "Generative AI": 2,
    Bioinformatics: 2,
    SAS: 1,
    "Data Science Tools": 1,
    "Clinical Data": 2,
    Research: 2,
    EDA: 2,
    SQL: 1,
    "BI Tools": 2,
    Metadata: 2,
    Governance: 2,
  },
  {
    name: "Rebecca Hodge",
    "Data Modeling": 3,
    "ETL/ELT": 1,
    "Cloud Data": 1,
    "Big Data": 2,
    Orchestration: 1,
    "Machine Learning": 2,
    MLOps: 2,
    "Deep Learning": 2,
    Statistics: 4,
    "Generative AI": 2,
    Bioinformatics: 4,
    SAS: 1,
    "Data Science Tools": 4,
    "Clinical Data": 2,
    Research: 4,
    EDA: 2,
    SQL: 2,
    "BI Tools": 2,
    Metadata: 1,
    Governance: 2,
  },
  {
    name: "Tom Recht",
    "Data Modeling": 3,
    "ETL/ELT": 3,
    "Cloud Data": 3,
    "Big Data": 3,
    Orchestration: 1,
    "Machine Learning": 4,
    MLOps: 3,
    "Deep Learning": 4,
    Statistics: 3,
    "Generative AI": 4,
    Bioinformatics: 1,
    SAS: 1,
    "Data Science Tools": 4,
    "Clinical Data": 1,
    Research: 1,
    EDA: 4,
    SQL: 3,
    "BI Tools": 3,
    Metadata: 1,
    Governance: 1,
  },
  {
    name: "Kinjal Madhu",
    "Data Modeling": 3,
    "ETL/ELT": 4,
    "Cloud Data": 3,
    "Big Data": 2,
    Orchestration: 2,
    "Machine Learning": 1,
    MLOps: 2,
    "Deep Learning": 1,
    Statistics: 2,
    "Generative AI": 2,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 1,
    "Clinical Data": 2,
    Research: 2,
    EDA: 5,
    SQL: 5,
    "BI Tools": 5,
    Metadata: 3,
    Governance: 4,
  },
  {
    name: "Lovekumar Patel",
    "Data Modeling": 3,
    "ETL/ELT": 1,
    "Cloud Data": 4,
    "Big Data": 4,
    Orchestration: 2,
    "Machine Learning": 4,
    MLOps: 1,
    "Deep Learning": 3,
    Statistics: 5,
    "Generative AI": 1,
    Bioinformatics: 1,
    SAS: 2,
    "Data Science Tools": 5,
    "Clinical Data": 1,
    Research: 2,
    EDA: 5,
    SQL: 5,
    "BI Tools": 3,
    Metadata: 5,
    Governance: 4,
  },
  {
    name: "shahed sabab",
    "Data Modeling": 3,
    "ETL/ELT": 4,
    "Cloud Data": 4,
    "Big Data": 4,
    Orchestration: 3,
    "Machine Learning": 5,
    MLOps: 4,
    "Deep Learning": 5,
    Statistics: 4,
    "Generative AI": 5,
    Bioinformatics: 1,
    SAS: 1,
    "Data Science Tools": 5,
    "Clinical Data": 3,
    Research: 4,
    EDA: 4,
    SQL: 4,
    "BI Tools": 4,
    Metadata: 4,
    Governance: 4,
  },
  {
    name: "Carlos Gomez",
    "Data Modeling": 5,
    "ETL/ELT": 5,
    "Cloud Data": 4,
    "Big Data": 4,
    Orchestration: 3,
    "Machine Learning": 1,
    MLOps: 3,
    "Deep Learning": 1,
    Statistics: 1,
    "Generative AI": 3,
    Bioinformatics: 4,
    SAS: 4,
    "Data Science Tools": 4,
    "Clinical Data": 4,
    Research: 4,
    EDA: 5,
    SQL: 5,
    "BI Tools": 5,
    Metadata: 5,
    Governance: 3,
  },
  {
    name: "Samuel Adams",
    "Data Modeling": 2,
    "ETL/ELT": 1,
    "Cloud Data": 1,
    "Big Data": 1,
    Orchestration: 1,
    "Machine Learning": 1,
    MLOps: 2,
    "Deep Learning": 2,
    Statistics: 3,
    "Generative AI": 2,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 1,
    "Clinical Data": 2,
    Research: 2,
    EDA: 5,
    SQL: 4,
    "BI Tools": 5,
    Metadata: 5,
    Governance: 5,
  },
  {
    name: "Lazaro Alvarez",
    "Data Modeling": 1,
    "ETL/ELT": 4,
    "Cloud Data": 5,
    "Big Data": 1,
    Orchestration: 4,
    "Machine Learning": 4,
    MLOps: 4,
    "Deep Learning": 4,
    Statistics: 3,
    "Generative AI": 5,
    Bioinformatics: 4,
    SAS: 3,
    "Data Science Tools": 5,
    "Clinical Data": 4,
    Research: 3,
    EDA: 3,
    SQL: 3,
    "BI Tools": 3,
    Metadata: 3,
    Governance: 3,
  },
  {
    name: "Siddharth Maheshwari",
    "Data Modeling": 3,
    "ETL/ELT": 4,
    "Cloud Data": 3,
    "Big Data": 3,
    Orchestration: 1,
    "Machine Learning": 4,
    MLOps: 1,
    "Deep Learning": 1,
    Statistics: 4,
    "Generative AI": 1,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 4,
    "Clinical Data": 2,
    Research: 2,
    EDA: 5,
    SQL: 4,
    "BI Tools": 5,
    Metadata: 4,
    Governance: 4,
  },
  {
    name: "Anant Sharma",
    "Data Modeling": 4,
    "ETL/ELT": 4,
    "Cloud Data": 4,
    "Big Data": 4,
    Orchestration: 4,
    "Machine Learning": 1,
    MLOps: 1,
    "Deep Learning": 2,
    Statistics: 2,
    "Generative AI": 3,
    Bioinformatics: 2,
    SAS: 3,
    "Data Science Tools": 1,
    "Clinical Data": 2,
    Research: 2,
    EDA: 3,
    SQL: 4,
    "BI Tools": 3,
    Metadata: 4,
    Governance: 4,
  },
  {
    name: "Umair Bhatti",
    "Data Modeling": 5,
    "ETL/ELT": 5,
    "Cloud Data": 5,
    "Big Data": 5,
    Orchestration: 5,
    "Machine Learning": 4,
    MLOps: 4,
    "Deep Learning": 1,
    Statistics: 1,
    "Generative AI": 3,
    Bioinformatics: 3,
    SAS: 4,
    "Data Science Tools": 4,
    "Clinical Data": 3,
    Research: 3,
    EDA: 4,
    SQL: 5,
    "BI Tools": 5,
    Metadata: 5,
    Governance: 5,
  },
  {
    name: "Qi (Jessica) Jiang",
    "Data Modeling": 3,
    "ETL/ELT": 3,
    "Cloud Data": 3,
    "Big Data": 3,
    Orchestration: 1,
    "Machine Learning": 1,
    MLOps: 2,
    "Deep Learning": 2,
    Statistics: 1,
    "Generative AI": 2,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 3,
    "Clinical Data": 2,
    Research: 2,
    EDA: 4,
    SQL: 4,
    "BI Tools": 4,
    Metadata: 4,
    Governance: 3,
  },
  {
    name: "Lily Liu",
    "Data Modeling": 3,
    "ETL/ELT": 3,
    "Cloud Data": 3,
    "Big Data": 3,
    Orchestration: 1,
    "Machine Learning": 4,
    MLOps: 4,
    "Deep Learning": 4,
    Statistics: 4,
    "Generative AI": 4,
    Bioinformatics: 2,
    SAS: 2,
    "Data Science Tools": 4,
    "Clinical Data": 2,
    Research: 3,
    EDA: 5,
    SQL: 5,
    "BI Tools": 5,
    Metadata: 5,
    Governance: 5,
  },
  {
    name: "Shreya Sharma",
    "Data Modeling": 4,
    "ETL/ELT": 3,
    "Cloud Data": 3,
    "Big Data": 1,
    Orchestration: 3,
    "Machine Learning": 3,
    MLOps: 2,
    "Deep Learning": 1,
    Statistics: 3,
    "Generative AI": 1,
    Bioinformatics: 5,
    SAS: 3,
    "Data Science Tools": 5,
    "Clinical Data": 2,
    Research: 3,
    EDA: 4,
    SQL: 4,
    "BI Tools": 4,
    Metadata: 2,
    Governance: 2,
  },
  {
    name: "Ahsaan Rizvi",
    "Data Modeling": 3,
    "ETL/ELT": 5,
    "Cloud Data": 3,
    "Big Data": 1,
    Orchestration: 1,
    "Machine Learning": 1,
    MLOps: 1,
    "Deep Learning": 1,
    Statistics: 3,
    "Generative AI": 1,
    Bioinformatics: 2,
    SAS: 1,
    "Data Science Tools": 4,
    "Clinical Data": 2,
    Research: 2,
    EDA: 5,
    SQL: 5,
    "BI Tools": 5,
    Metadata: 1,
    Governance: 4,
  },
];
