import { Data } from "@/utils";

export const groupsData: Data = [
  {
    name: "Data Scientist",
    "Data Modeling": 1,
    "ETL/ELT": 1,
    "Cloud Data": 1,
    "Big Data": 1,
    Orchestration: 1,
    "Machine Learning": 5,
    MLOps: 4,
    "Deep Learning": 5,
    Statistics: 4,
    "Generative AI": 4,
    Bioinformatics: 1,
    SAS: 1,
    "Data Science Tools": 3,
    "Clinical Data": 1,
    Research: 2,
    EDA: 3,
    SQL: 2,
    "BI Tools": 2,
    Metadata: 1,
    Governance: 1,
  },
  {
    name: "Data Engineering",
    "Data Modeling": 5,
    "ETL/ELT": 4,
    "Cloud Data": 5,
    "Big Data": 4,
    Orchestration: 5,
    "Machine Learning": 2,
    MLOps: 3,
    "Deep Learning": 2,
    Statistics: 1,
    "Generative AI": 2,
    Bioinformatics: 1,
    SAS: 2,
    "Data Science Tools": 2,
    "Clinical Data": 2,
    Research: 1,
    EDA: 2,
    SQL: 3,
    "BI Tools": 2,
    Metadata: 3,
    Governance: 1,
  },
  {
    name: "Data Governance",
    "Data Modeling": 2,
    "ETL/ELT": 1,
    "Cloud Data": 2,
    "Big Data": 2,
    Orchestration: 1,
    "Machine Learning": 2,
    MLOps: 2,
    "Deep Learning": 1,
    Statistics: 1,
    "Generative AI": 1,
    Bioinformatics: 4,
    SAS: 2,
    "Data Science Tools": 2,
    "Clinical Data": 4,
    Research: 4,
    EDA: 1,
    SQL: 1,
    "BI Tools": 3,
    Metadata: 4,
    Governance: 5,
  },
  {
    name: "Data Analysis",
    "Data Modeling": 2,
    "ETL/ELT": 1,
    "Cloud Data": 1,
    "Big Data": 1,
    Orchestration: 1,
    "Machine Learning": 2,
    MLOps: 1,
    "Deep Learning": 1,
    Statistics: 5,
    "Generative AI": 1,
    Bioinformatics: 2,
    SAS: 3,
    "Data Science Tools": 5,
    "Clinical Data": 2,
    Research: 3,
    EDA: 5,
    SQL: 4,
    "BI Tools": 4,
    Metadata: 2,
    Governance: 2,
  },
];
