import { Data } from "../utils";

export const dataScientistTypeData: Data = [
  {
    "Cloud Computing & DevOps": 71,
    "Data Engineering & ETL": 90,
    "Programming Languages": 63,
    "Data Science & Machine Learning": 33,
    "Databases & Storage": 83,
    "Data Visualization & BI": 4,
    "Big Data & Streaming": 62,
    "DevOps & CI/CD": 88,
    "R Ecosystem": 4,
    "Web & Frontend": 3,
    "Other": 4,
    name: 'Data Engineer',
  },
  {
    "Cloud Computing & DevOps": 3.125,
    "Data Engineering & ETL": 5,
    "Programming Languages": 10.7143,
    "Data Science & Machine Learning": 99,
    "Databases & Storage": 8.3333,
    "Data Visualization & BI": 67,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 70,
    "Web & Frontend": 18.3333,
    "Other": 23.25,
    name: 'ML Engineer',
  },
  {
    "Cloud Computing & DevOps": 3.125,
    "Data Engineering & ETL": 35,
    "Programming Languages": 10.7143,
    "Data Science & Machine Learning": 91.4706,
    "Databases & Storage": 8.3333,
    "Data Visualization & BI": 71.25,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 83.125,
    "Web & Frontend": 8.3333,
    "Other": 23.25,
    name: 'Data Scientist',
  },
  {
    "Cloud Computing & DevOps": 3.125,
    "Data Engineering & ETL": 5,
    "Programming Languages": 90.7143,
    "Data Science & Machine Learning": 1.4706,
    "Databases & Storage": 8.3333,
    "Data Visualization & BI": 91.25,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 93.125,
    "Web & Frontend": 48.3333,
    "Other": 23.25,
    name: 'Data Analyst',
  },
];

export const employeesData: Data = [
  {
    "Cloud Computing & DevOps": 3.125,
    "Data Engineering & ETL": 5,
    "Programming Languages": 10.7143,
    "Data Science & Machine Learning": 1.4706,
    "Databases & Storage": 8.3333,
    "Data Visualization & BI": 31.25,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 3.125,
    "Web & Frontend": 8.3333,
    "Other": 23.25,
    "name": "Bill Carney"
  },
  {
    "Cloud Computing & DevOps": 12.5,
    "Data Engineering & ETL": 7.5,
    "Programming Languages": 28.5714,
    "Data Science & Machine Learning": 7.3529,
    "Databases & Storage": 8.3333,
    "Data Visualization & BI": 8.3333,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 25,
    "R Ecosystem": 90.625,
    "Web & Frontend": 8.3333,
    "Other": 0,
    "name": "Brian Carter"
  },
  {
    "Cloud Computing & DevOps": 10.9375,
    "Data Engineering & ETL": 2.5,
    "Programming Languages": 32.1429,
    "Data Science & Machine Learning": 39.7059,
    "Databases & Storage": 14.5833,
    "Data Visualization & BI": 22.9167,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 11.1111,
    "R Ecosystem": 34.375,
    "Web & Frontend": 25,
    "Other": 0,
    "name": "Tom Harding"
  },
  {
    "Cloud Computing & DevOps": 6.25,
    "Data Engineering & ETL": 2.5,
    "Programming Languages": 32.1429,
    "Data Science & Machine Learning": 39.7059,
    "Databases & Storage": 14.5833,
    "Data Visualization & BI": 14.5833,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 8.3333,
    "R Ecosystem": 31.25,
    "Web & Frontend": 16.6667,
    "Other": 0,
    "name": "Ned Booker"
  },
  {
    "Cloud Computing & DevOps": 26.5625,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 2.0833,
    "Big Data & Streaming": 30,
    "DevOps & CI/CD": 52.7778,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Lazaro Alvarez"
  },
  {
    "Cloud Computing & DevOps": 17.1875,
    "Data Engineering & ETL": 47.5,
    "Programming Languages": 28.5714,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 45.8333,
    "Data Visualization & BI": 8.3333,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 13.8889,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Ois�n Bates"
  },
  {
    "Cloud Computing & DevOps": 18.75,
    "Data Engineering & ETL": 0,
    "Programming Languages": 21.4286,
    "Data Science & Machine Learning": 67.6471,
    "Databases & Storage": 6.25,
    "Data Visualization & BI": 16.6667,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 6.25,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Shahed Anzarus Sabab"
  },
  {
    "Cloud Computing & DevOps": 6.25,
    "Data Engineering & ETL": 2.5,
    "Programming Languages": 42.8571,
    "Data Science & Machine Learning": 16.1765,
    "Databases & Storage": 14.5833,
    "Data Visualization & BI": 8.3333,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 11.1111,
    "R Ecosystem": 75,
    "Web & Frontend": 50,
    "Other": 0,
    "name": "Gabriel Brock"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "Siavash"
  },
  {
    "Cloud Computing & DevOps": 21.875,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 2.0833,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 30.5556,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Samuel Adams"
  },
  {
    "Cloud Computing & DevOps": 57.8125,
    "Data Engineering & ETL": 17.5,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 8.3333,
    "Data Visualization & BI": 4.1667,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 50,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Momin Musab Umair"
  },
  {
    "Cloud Computing & DevOps": 17.1875,
    "Data Engineering & ETL": 47.5,
    "Programming Languages": 17.8571,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 37.5,
    "Data Visualization & BI": 8.3333,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 8.3333,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Anant sharma"
  },
  {
    "Cloud Computing & DevOps": 6.25,
    "Data Engineering & ETL": 2.5,
    "Programming Languages": 28.5714,
    "Data Science & Machine Learning": 20.5882,
    "Databases & Storage": 18.75,
    "Data Visualization & BI": 14.5833,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 11.1111,
    "R Ecosystem": 25,
    "Web & Frontend": 50,
    "Other": 0,
    "name": "Justin Lam"
  },
  {
    "Cloud Computing & DevOps": 26.5625,
    "Data Engineering & ETL": 40,
    "Programming Languages": 39.2857,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 35.4167,
    "Data Visualization & BI": 8.3333,
    "Big Data & Streaming": 20,
    "DevOps & CI/CD": 8.3333,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Sarbjit Sarkaria"
  },
  {
    "Cloud Computing & DevOps": 4.6875,
    "Data Engineering & ETL": 20,
    "Programming Languages": 32.1429,
    "Data Science & Machine Learning": 1.4706,
    "Databases & Storage": 27.0833,
    "Data Visualization & BI": 52.0833,
    "Big Data & Streaming": 25,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 3.125,
    "Web & Frontend": 25,
    "Other": 33.3333,
    "name": "Priya Tanwar"
  },
  {
    "Cloud Computing & DevOps": 6.25,
    "Data Engineering & ETL": 2.5,
    "Programming Languages": 21.4286,
    "Data Science & Machine Learning": 11.7647,
    "Databases & Storage": 12.5,
    "Data Visualization & BI": 10.4167,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 5.5556,
    "R Ecosystem": 25,
    "Web & Frontend": 25,
    "Other": 0,
    "name": "Tom Recht"
  },
  {
    "Cloud Computing & DevOps": 34.375,
    "Data Engineering & ETL": 77.5,
    "Programming Languages": 39.2857,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 58.3333,
    "Data Visualization & BI": 16.6667,
    "Big Data & Streaming": 10,
    "DevOps & CI/CD": 13.8889,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Umair Bhatti"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Lily Liu"
  },
  {
    "Cloud Computing & DevOps": 25,
    "Data Engineering & ETL": 30,
    "Programming Languages": 17.8571,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 27.0833,
    "Data Visualization & BI": 8.3333,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 5.5556,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Sai Sunhith Gaddam"
  },
  {
    "Cloud Computing & DevOps": 3.125,
    "Data Engineering & ETL": 5,
    "Programming Languages": 10.7143,
    "Data Science & Machine Learning": 1.4706,
    "Databases & Storage": 18.75,
    "Data Visualization & BI": 39.5833,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 3.125,
    "Web & Frontend": 8.3333,
    "Other": 16.6667,
    "name": "Jens Sommerfeld"
  },
  {
    "Cloud Computing & DevOps": 4.6875,
    "Data Engineering & ETL": 15,
    "Programming Languages": 17.8571,
    "Data Science & Machine Learning": 1.4706,
    "Databases & Storage": 20.8333,
    "Data Visualization & BI": 50,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 3.125,
    "Web & Frontend": 8.3333,
    "Other": 33.3333,
    "name": "Kinjal Madhu"
  },
  {
    "Cloud Computing & DevOps": 26.5625,
    "Data Engineering & ETL": 62.5,
    "Programming Languages": 35.7143,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 54.1667,
    "Data Visualization & BI": 12.5,
    "Big Data & Streaming": 20,
    "DevOps & CI/CD": 11.1111,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Mehdi Nikkhah"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Carlos Gomez Hernandez"
  },
  {
    "Cloud Computing & DevOps": 18.75,
    "Data Engineering & ETL": 47.5,
    "Programming Languages": 21.4286,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 37.5,
    "Data Visualization & BI": 10.4167,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 5.5556,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Akshay Veeramaneni"
  },
  {
    "Cloud Computing & DevOps": 4.6875,
    "Data Engineering & ETL": 2.5,
    "Programming Languages": 21.4286,
    "Data Science & Machine Learning": 13.2353,
    "Databases & Storage": 12.5,
    "Data Visualization & BI": 14.5833,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 5.5556,
    "R Ecosystem": 25,
    "Web & Frontend": 16.6667,
    "Other": 0,
    "name": "Ahsaan Rizvi"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Qi Jiang (Jessica)"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Sharmistha Ganguly Ghosh"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Greg"
  },
  {
    "Cloud Computing & DevOps": 3.125,
    "Data Engineering & ETL": 12.5,
    "Programming Languages": 25,
    "Data Science & Machine Learning": 4.4118,
    "Databases & Storage": 18.75,
    "Data Visualization & BI": 56.25,
    "Big Data & Streaming": 25,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 3.125,
    "Web & Frontend": 8.3333,
    "Other": 33.3333,
    "name": "Chuck Ho"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Becky"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "Sailanki"
  },
  {
    "Cloud Computing & DevOps": 3.125,
    "Data Engineering & ETL": 7.5,
    "Programming Languages": 17.8571,
    "Data Science & Machine Learning": 1.4706,
    "Databases & Storage": 14.5833,
    "Data Visualization & BI": 43.75,
    "Big Data & Streaming": 15,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 3.125,
    "Web & Frontend": 8.3333,
    "Other": 25,
    "name": "Aline Santoso"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Lovekumar Patel"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 0,
    "name": "Jose Sergio Hleap"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 3.25,
    "name": "Jaspreet Oberoi"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "Shuyu"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "Shreya"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "Videesh"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "Siva"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "Sahib"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "Nancy"
  },
  {
    "Cloud Computing & DevOps": 0,
    "Data Engineering & ETL": 0,
    "Programming Languages": 0,
    "Data Science & Machine Learning": 0,
    "Databases & Storage": 0,
    "Data Visualization & BI": 0,
    "Big Data & Streaming": 0,
    "DevOps & CI/CD": 0,
    "R Ecosystem": 0,
    "Web & Frontend": 0,
    "Other": 1.5,
    "name": "JP"
  }
]

